language: objective-c
osx_image: xcode8.3
sudo: false

cache:
  directories:
  - Carthage
  - Inspector/node_modules

script: ./Scripts/build.sh

branches:
  only:
    - master

env:
# Builds (iphone & ipad)
- ACTION=build DEST=iphone TARGET=runner SDK=sim
- ACTION=build DEST=iphone TARGET=runner SDK=device

# Builds (tvos)
- ACTION=build DEST=tvos TARGET=runner SDK=sim
- ACTION=build DEST=tvos TARGET=runner SDK=device

# Analyze (iphone & ipad)
- ACTION=analyze DEST=iphone TARGET=lib SDK=sim
- ACTION=analyze DEST=iphone TARGET=runner SDK=sim

# Analyze (tvos)
- ACTION=analyze DEST=tvos TARGET=lib SDK=sim
- ACTION=analyze DEST=tvos TARGET=runner SDK=sim

# Unit tests
- ACTION=unit_test DEST=iphone TARGET=lib SDK=sim
- ACTION=unit_test DEST=ipad TARGET=lib SDK=sim
- ACTION=unit_test DEST=tvos TARGET=lib SDK=sim

# Integration tests iPhone
- ACTION=int_test_1 DEST=iphone TARGET=lib SDK=sim
- ACTION=int_test_2 DEST=iphone TARGET=lib SDK=sim
- ACTION=int_test_3 DEST=iphone TARGET=lib SDK=sim

# Integration tests iPad
- ACTION=int_test_1 DEST=ipad TARGET=lib SDK=sim
- ACTION=int_test_2 DEST=ipad TARGET=lib SDK=sim
- ACTION=int_test_3 DEST=ipad TARGET=lib SDK=sim

# Integration tests tvOS
- ACTION=int_test_1 DEST=tvos TARGET=lib SDK=sim
- ACTION=int_test_2 DEST=tvos TARGET=lib SDK=sim
- ACTION=int_test_3 DEST=tvos TARGET=lib SDK=sim
