language: objective-c
osx_image: xcode7.3
before_install:
  brew install carthage

script: ./Scripts/build.sh

branches:
  only:
    - master

env:
- PROJECT=WebDriverAgent.xcodeproj TARGET=WebDriverAgentLib SDK=iphonesimulator ACTION=test
- PROJECT=WebDriverAgent.xcodeproj TARGET=WebDriverAgentRunner SDK=iphonesimulator ACTION=build
- PROJECT=WebDriverAgent.xcodeproj TARGET=WebDriverAgentRunner SDK=iphoneos ACTION=build
