language: objective-c
osx_image: xcode8
sudo: false

cache:
  directories:
  - Carthage

script: ./Scripts/build.sh

branches:
  only:
    - master

env:
- TARGET=WebDriverAgentLib SDK=iphonesimulator DESTINATION='iPad Air 2 (10.0)' ACTION=test
- TARGET=WebDriverAgentLib SDK=iphonesimulator DESTINATION='iPhone SE (10.0)' ACTION=test
- TARGET=WebDriverAgentRunner SDK=iphonesimulator ACTION=build
- TARGET=WebDriverAgentRunner SDK=iphoneos ACTION=build
- TARGET=WebDriverAgentUSBClient SDK=macosx ACTION=build
